####################################################################################################
## 如何使用该配置文件, 进行自定义任务的提交:
## # volc ml_task submit -c job_conf_example.yaml
## Volc 命令行支持使用 --set 对配置文件中的配置项进行复写. 举例如下:
## $ volc ml_task submit -c job_conf_example.yaml --set TaskName=yyy --set Tags={a,b,c} 
## 上述命令将会把任务配置文件中的 TaskName 替换成 yyy, Tags 替换成 
## Tags:
##  - "a"
##  - "b"
##  - "c"
## 其中 --set 支持多个字段的复写或者用 ',' 分割的多个配置项, 例如 '--set a=1 --set b=2' 和 '--set a=1,b=2' 等价
####################################################################################################
# 自定义训练任务名称
TaskName: "一个示例的自定义任务名字"
# 自定义训练任务描述
Description: "对这个自定义任务的描述"
# 标签
Tags:
    - "example"
# 待上传代码的本地路径, 如是目录且以 '/' 结尾, 则将该目录下的所有内容上传到 RemoteMountCodePath,
# 如是目录且不以 '/' 结尾, 则将该目录及该目录下所有内容上传到 RemoteMountCodePath
UserCodePath: "./"
# 容器中的代码挂载路径
RemoteMountCodePath: "/root/code"
# 入口命令
Entrypoint: "echo 'hello world' && sleep 900"
# 环境变量
Envs:
    - Name: "key1"
      Value: "value1"
# 镜像 URL 地址, 执行任务时, 会自动下载该地址的镜像并使用
ImageUrl: "cr-cn-beijing.volces.com/ml_platform/python:cuda10.2"
# 当 ImageUrl 为私有仓库的镜像时, 需填写仓库的用户名和密钥才能拉取镜像, 可反注释下方三行进行配置
# ImageCredential:
#     RegistryUsername: "some user"
#     RegistryToken: "some token"

# 提交到火山引擎机器学习平台的某个队列, 可以访问 https://console.volcengine.com/ml-platform/resourceQueue 查看有权限的队列
ResourceQueueName: "some_xx_queue_name"
# 训练框架，支持 TensorFlowPS / PyTorchDDP / MPI / BytePS / Custom
Framework: "Custom"
# 实例配置, 包含角色名称(RoleName), 角色数量(RoleReplicas)以及具体的实例规格(Flavor)
TaskRoleSpecs:
    - RoleName: "worker"
      RoleReplicas: 1
      Flavor: "ml.g1ie.large"
# 该自定义任务最长运行时间, 支持 1h, 2h45m, 30s 等方式表达时间段, 如未带单位, 则默认单位为秒
ActiveDeadlineSeconds: "1h"
# 实例保留时长, 注释下方配置配置保留 1 小时, 默认不保留. 该配置主要用于调试和定位问题. 其值的格式和 ActiveDeadlineSeconds 一致.
# DelayExitTimeSeconds: "1h"
# 是否开启 TensorBoard. 如需开启, 则可以反注释下方配置. 同时需将 TensorBoard 数据写入训练容器预置的环境变量($TENSORBOARD_LOG_PATH)下
# EnableTensorBoard: true
# 挂载分布式数据盘至训练容器中, 支持 Tos, vePFS 等数据盘挂载方式.
# Storages:
#     - Type: "Tos" # 可以是 Tos 或者 vePFS.
#       MountPath: "/path/to/xxx" # 在分布式训练容器中挂载的路径
#       Bucket: "replace_with_tos_bucket_name" # 可访问的 tos 下某个具体的 bucket 名字, 例如: default_bucket.
#       Prefix: "replace_with_bucket_prefix_path" # 替换成 bucket 下某个具体的路径, 例如 /mlp_assets/images
# 可见范围，支持 Public / Queue / Private
AccessType: "Public"
# 可见用户列表, 注释下方两行可以配置, 注意: 如可见范围为 Private/Public, 则可见用户列表不生效
# AccessUsers:
#     - "username_a"
#     - "username_b"